# dependencies:
#   pre:
#     # Install the latest stable PlatformIO
#     - sudo pip install -U platformio

#     # download dependent libraries
#     - platformio lib -g install 1 # OneWire
#     - platformio lib -g install 251 # VirtualWire
#     - platformio lib -g install 38 # LowPower

# test:
#   override:
#       - platformio ci src/thermo.cpp --board=pro8MHzatmega328


version: 2
jobs:
  build:
    docker:
      - image: suculent/platformio-docker-build
    steps:
      - run: wget https://github.com/bigjosh/OneWireNoResistor/archive/master.zip -O /tmp/OneWireNoResistor.zip
      - run: unzip /tmp/OneWireNoResistor.zip -d $PWD/lib/
      - checkout
      - run: platformio lib -g install 251 # VirtualWire
      - run: platformio lib -g install 38 # LowPower
      - run: platformio ci src/thermo.cpp --board=pro8MHzatmega328
      