version: 2
jobs:
  build-code:
    docker:
      - image: petewall/platformio
    steps:
      - checkout
      - run: 
          command: platformio lib -g install 251 # VirtualWire
          name: Lib VirtualWire installing
      - run: 
          command: platformio lib -g install 38 # LowPower
          name: Lib LowPower installing
      - run: 
          command: platformio ci src/thermo.cpp --board=pro8MHzatmega328 --lib=lib/OneWireNoResistor --lib=include/const.h --lib=include/struct.h
          name: Build

workflows:
  build:
    jobs:
    - build-code
  version: 2
      