version: 2
jobs:
  build:
    docker:
      - image: suculent/platformio-docker-build
    steps:
      - checkout
      - run: platformio lib -g install 251 # VirtualWire
      - run: platformio lib -g install 38 # LowPower
      - run: platformio ci src/thermo.cpp --board=pro8MHzatmega328