# dependencies:
#   pre:
#     # Install the latest stable PlatformIO
#     - sudo pip install -U platformio

#     # download dependent libraries
#     - platformio lib -g install 1 # OneWire
#     - platformio lib -g install 251 # VirtualWire
#     - platformio lib -g install 38 # LowPower

# test:
#   override:
#       - platformio ci src/thermo.cpp --board=pro8MHzatmega328


version: 2
jobs:
  build-code:
    docker:
      - image: petewall/platformio
    steps:
      - checkout
      - run: 
          command: platformio lib -g install 251 # VirtualWire
          name: Lib VirtualWire installing
      - run: 
          command: platformio lib -g install 38 # LowPower
          name: Lib LowPower installing
      - run: 
          command: platformio ci src/thermo.cpp --board=pro8MHzatmega328 --lib=lib/OneWireNoResistor
          name: Build

workflows:
  build:
    jobs:
    - build-code
  version: 2
      