# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orchestrate or schedule a set of jobs
workflows:

  jobs:
    build-arduino-default:
      machine: true
      steps:
        - checkout
        - run:
            name: Make scripts executable 
            command: sudo chmod -R +x ./.circleci/*.sh
        - run:
            name: Install
            command: ./.circleci/install_arduino.sh
        - run:
            name: Build
            command: ./.circleci/script_arduino.sh

  workflows:
    build:
      jobs:
        - build-arduino-default