version: 2
jobs:
  build-code:
    docker:
      - image: petewall/platformio
    steps:
      - checkout
      - run:
          command: pio pkg update
          name: Updating platformio
      # - run: 
      #     command: platformio lib -g install 251 # VirtualWire
      #     name: Lib VirtualWire installing
      # - run: 
      #     command: platformio lib -g install 38 # LowPower
      #     name: Lib LowPower installing
      - run: 
          command: platformio check --project-conf=platformio.ini --fail-on-defect=medium --fail-on-defect=high
          name: Check defects >= medium
      - run:
          command: platformio run --environment=DEBUG
          name: Build-DEBUG 
      - run:
          command: platformio run --environment=RELEASE
          name: Build-RELEASE
workflows:
  build:
    jobs:
    - build-code
  version: 2
  
      
