version: 2
jobs:
  build-code:
    docker:
      - image: cimg/base:2024.12
    steps:
      - run: curl -fsSL -o get-platformio.py https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py python3 get-platformio.py
      - run: wget -O get-platformio.py https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py python3 get-platformio.py
      - checkout
      - run:
          command: pio pkg update
          name: Updating platformio
      # - run: 
      #     command: platformio lib -g install 251 # VirtualWire
      #     name: Lib VirtualWire installing
      # - run: 
      #     command: platformio lib -g install 38 # LowPower
      #     name: Lib LowPower installing
      - run: 
          command: pio check --skip-packages -v --project-conf=platformio.ini --fail-on-defect=medium --fail-on-defect=high
          name: Check defects >= medium
      - run:
          command: pio run --environment=DEBUG
          name: Build-DEBUG 
      - run:
          command: pio run --environment=RELEASE
          name: Build-RELEASE
workflows:
  build:
    jobs:
    - build-code
  version: 2
  
      
